# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MailConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("client_id", models.CharField(max_length=255)),
                ("authority_url", models.URLField(max_length=500)),
                ("client_secret_value", models.TextField()),
                ("email_sender", models.EmailField(max_length=254)),
                ("email_sender_name", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField(help_text="HTML body")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipients",
                    models.ManyToManyField(blank=True, related_name="mail_configurations", to="mailer.mailrecipient"),
                ),
            ],
        ),
    ]
