# Generated by Django 6.0.2 on 2026-03-22 23:45

import mailer.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailconfiguration",
            name="client_secret_value",
            field=mailer.fields.EncryptedTextField(),
        ),
    ]
