# Generated by Django 6.0.2 on 2026-02-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=255)),
                ("long_name", models.CharField(max_length=255)),
                ("west_bound_longitude", models.FloatField(blank=True, null=True)),
                ("east_bound_longitude", models.FloatField(blank=True, null=True)),
                ("south_bound_latitude", models.FloatField(blank=True, null=True)),
                ("north_bound_latitude", models.FloatField(blank=True, null=True)),
                ("crs", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
