# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0001_initial"),
        ("region", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="regions",
            field=models.ManyToManyField(blank=True, related_name="countries", to="region.region"),
        ),
    ]
