# Generated by Django 6.0.2 on 2026-02-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CycloneTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cyclone_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issued_time", models.DateTimeField(blank=True, null=True)),
                (
                    "issued_agency",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("track_file", models.FileField(upload_to="cyclone_tracks/")),
                ("geometry", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
