# Generated by Django 6.0.2 on 2026-03-05

from django.db import migrations, models


def _is_blank_geometry(value) -> bool:
    if value is None:
        return True
    if isinstance(value, list):
        return len(value) == 0
    if isinstance(value, dict):
        if len(value) == 0:
            return True
        features = value.get("features")
        if isinstance(features, list) and len(features) == 0:
            return True
    return False


def forwards(apps, schema_editor):
    CycloneTrack = apps.get_model("cyclone_track", "CycloneTrack")

    for track in CycloneTrack.objects.all().only("id", "geometry").iterator():
        computed = not _is_blank_geometry(track.geometry)
        if computed:
            CycloneTrack.objects.filter(pk=track.pk).update(geometry_computed=True)


def backwards(apps, schema_editor):
    CycloneTrack = apps.get_model("cyclone_track", "CycloneTrack")
    CycloneTrack.objects.all().update(geometry_computed=False)


class Migration(migrations.Migration):

    dependencies = [
        ("cyclone_track", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyclonetrack",
            name="geometry_computed",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards, backwards),
    ]
