# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ("cyclone_track", "0002_cyclonetrack_geometry_computed"),
        ("country", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyclonetrack",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cyclone_tracks",
                to="country.country",
            ),
        ),
    ]
