# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0001_initial"),
        ("cyclone_track", "0003_cyclonetrack_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyclonetrack",
            name="notify",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cyclonetrack",
            name="mail_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cyclone_tracks",
                to="mailer.mailconfiguration",
            ),
        ),
    ]
