# Generated by Django 6.0.2 on 2026-04-28 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyclone_track", "0004_cyclonetrack_notify_mail_configuration"),
        ("cyclone_track_type", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyclonetrack",
            name="cyclone_track_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cyclone_tracks",
                to="cyclone_track_type.cyclonetracktype",
            ),
        ),
    ]
