"""
Django settings for middleware_partner_api project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _getenv_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


def _getenv_list(name: str, default: list[str]) -> list[str]:
    value = os.getenv(name)
    if not value:
        return default
    return [item.strip() for item in value.split(",") if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-lymg9)8=_5s3yhdbgol#z&6pdaz5&8f30!o2%38ofhc_%gun5)",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _getenv_bool("DJANGO_DEBUG", True)

CSRF_TRUSTED_ORIGINS = _getenv_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    ["https://*.spc.int", "http://localhost*"],
)

ALLOWED_HOSTS = _getenv_list("DJANGO_ALLOWED_HOSTS", ["*"])
CORS_ALLOW_ALL_ORIGINS = _getenv_bool("CORS_ALLOW_ALL_ORIGINS", True)


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # Access token expiry time
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),   
}

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': timedelta(days=1),  # Access token expiry time
    'JWT_REFRESH_EXPIRATION_DELTA': timedelta(days=1)
}
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'django_filters',
    'country',
    'cyclone_track',
    'island',
    'project',
    'hazard_type',
    'hazard_information',
    'region',
    'risk_category',
    'risk_information',
    'event_type.apps.EventTypeConfig',
    'citizen_science',
    'event',
    'mailer.apps.MailerConfig',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "middleware_partner_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "middleware_partner_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
"""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
"""
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'partner-api',
        'USER': 'postgres',
        'PASSWORD': 'Oceanportal2017*',
        #'HOST': 'db',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB')
        or os.getenv('POSTGRESDB_DATABASE')
        or 'partner-api',
        'USER': os.getenv('POSTGRES_USER')
        or os.getenv('POSTGRESDB_USER')
        or 'postgres',
        'PASSWORD': os.getenv('POSTGRES_PASSWORD')
        or os.getenv('POSTGRESDB_ROOT_PASSWORD')
        or 'Oceanportal2017*',
        'HOST': os.getenv('POSTGRES_HOST')
        or os.getenv('POSTGRESDB_HOST')
        or os.getenv('DJANGO_DB_HOST')
        or 'localhost',
        'PORT': os.getenv('POSTGRES_PORT')
        or os.getenv('POSTGRESDB_DOCKER_PORT')
        or os.getenv('DJANGO_DB_PORT')
        or '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Optional: override the encryption key used for mail configuration secrets.
# If not provided, SECRET_KEY is used as the key material.
MAIL_CONFIG_ENCRYPTION_KEY = os.getenv("MAIL_CONFIG_ENCRYPTION_KEY")

# Optional: default MailConfiguration name to use when calling
# SPCMailer.send_notification_email_sync(to, subject, body) without specifying a config.
MAILER_DEFAULT_CONFIGURATION_NAME = os.getenv("MAILER_DEFAULT_CONFIGURATION_NAME")
