# Generated by Django 6.0.2 on 2026-03-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_type", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
