# Generated by Django 6.0.2 on 2026-03-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event_type", "0002_alter_eventtype_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventType",
            new_name="HazardType",
        ),
        migrations.RenameField(
            model_name="hazardtype",
            old_name="event_type",
            new_name="hazard_type",
        ),
    ]
