# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("country", "0001_initial"),
        ("cyclone_track", "0003_cyclonetrack_country"),
        ("hazard_information", "0005_hazardinformation_event_type"),
        ("risk_information", "0006_riskinformation_event_type"),
        ("citizen_science", "0001_initial"),
        ("event_type_v2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="country.country",
                    ),
                ),
                (
                    "cyclone_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="cyclone_track.cyclonetrack",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="event_type_v2.eventtype",
                    ),
                ),
            ],
            options={
                "db_table": "event",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="citizen_sciences",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                to="citizen_science.citizenscience",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="hazards",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                to="hazard_information.hazardinformation",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="risks",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                to="risk_information.riskinformation",
            ),
        ),
    ]
