# Generated by Django 6.0.2 on 2026-03-23 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyclone_track", "0004_cyclonetrack_notify_mail_configuration"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cyclone_track",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="cyclone_track.cyclonetrack",
            ),
        ),
    ]
