# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0003_modelrun_models_m2m"),
        ("event", "0002_alter_event_cyclone_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="model_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="model.modelrun",
            ),
        ),
    ]
