# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cyclone_track", "0004_cyclonetrack_notify_mail_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"db_table": "model_domain"},
        ),
        migrations.CreateModel(
            name="ModelPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"db_table": "model_priority"},
        ),
        migrations.CreateModel(
            name="ModelStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"db_table": "model_status"},
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=500)),
                ("server_name", models.CharField(blank=True, max_length=255)),
                ("inputs", models.JSONField(blank=True, null=True)),
                ("dry_run_command", models.TextField(blank=True)),
            ],
            options={"db_table": "model"},
        ),
        migrations.CreateModel(
            name="ModelRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "model_domain",
                    models.ForeignKey(
                        db_column="model_domain_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="model.modeldomain",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        db_column="model_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="model.model",
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="model.modelpriority",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="model.modelstatus",
                    ),
                ),
                (
                    "tc_track",
                    models.ForeignKey(
                        db_column="tc_track_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_runs",
                        to="cyclone_track.cyclonetrack",
                    ),
                ),
            ],
            options={"db_table": "model_run"},
        ),
        migrations.CreateModel(
            name="ModelLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logs", models.TextField()),
                (
                    "model_run",
                    models.ForeignKey(
                        db_column="model_run_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="model.modelrun",
                    ),
                ),
            ],
            options={"db_table": "model_logs"},
        ),
    ]
