# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations, models
import django.db.models.deletion


def copy_run_status_to_logs(apps, schema_editor):
    ModelRun = apps.get_model("model", "ModelRun")
    ModelLogs = apps.get_model("model", "ModelLogs")

    # If the old ModelRun.status column exists (this migration runs before RemoveField),
    # copy it into ModelLogs.status for existing rows.
    for run in ModelRun.objects.all().only("id", "status_id"):
        if not getattr(run, "status_id", None):
            continue

        # Update existing logs first
        updated = ModelLogs.objects.filter(model_run_id=run.id, status__isnull=True).update(
            status_id=run.status_id
        )
        if updated:
            continue

        # If there are no logs at all, create one so status isn't lost.
        if not ModelLogs.objects.filter(model_run_id=run.id).exists():
            ModelLogs.objects.create(
                model_run_id=run.id,
                status_id=run.status_id,
                logs="",
            )


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modellogs",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="log_entries",
                to="model.modelstatus",
            ),
        ),
        migrations.RunPython(copy_run_status_to_logs, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="modelrun",
            name="status",
        ),
    ]
