# Generated by Django 6.0.2 on 2026-03-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modellogs",
            options={"verbose_name": "Model log", "verbose_name_plural": "Model logs"},
        ),
        migrations.AlterModelOptions(
            name="modelstatus",
            options={
                "verbose_name": "Model status",
                "verbose_name_plural": "Model status",
            },
        ),
    ]
