# Generated by Django 6.0.2 on 2026-03-23 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0002_alter_modellogs_options_alter_modelstatus_options"),
        ("model", "0002_move_status_to_logs"),
    ]

    operations = []
