# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations, models


def copy_single_model_to_m2m(apps, schema_editor):
    ModelRun = apps.get_model("model", "ModelRun")
    Model = apps.get_model("model", "Model")

    through = ModelRun._meta.get_field("models").remote_field.through

    # Copy existing model_id values (from old FK column) into the M2M.
    for run in ModelRun.objects.all().only("id", "model_id"):
        model_id = getattr(run, "model_id", None)
        if not model_id:
            continue
        if Model.objects.filter(id=model_id).exists():
            through.objects.get_or_create(modelrun_id=run.id, model_id=model_id)


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0002_move_status_to_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelrun",
            name="models",
            field=models.ManyToManyField(blank=True, related_name="runs", to="model.model"),
        ),
        migrations.RunPython(copy_single_model_to_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="modelrun",
            name="model",
        ),
    ]
