# Generated by Django 6.0.2 on 2026-03-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0003_merge_20260323_0312"),
        ("model", "0003_modelrun_models_m2m"),
    ]

    operations = []
