# Generated by Django 6.0.2 on 2026-03-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0004_merge_20260323_0316"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelrun",
            options={"ordering": ("-id",)},
        ),
    ]
