# Generated by Django 6.0.2 on 2026-03-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0005_alter_modelrun_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelrun",
            name="model_run_completed",
            field=models.BooleanField(default=False),
        ),
    ]
