# Generated by Django 6.0.2 on 2026-03-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hazard_information", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hazardinformation",
            name="style",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
