# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hazard_information", "0002_alter_hazardinformation_style"),
        # hazard_type app uses label "event_type" for migration continuity
        ("event_type", "0003_rename_eventtype_to_hazardtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="hazardinformation",
            name="hazard_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hazard_information",
                to="event_type.hazardtype",
            ),
        ),
    ]
