# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies = [
        ("hazard_information", "0003_hazardinformation_hazard_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="hazardinformation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
    ]
