# Generated by Django 6.0.2 on 2026-03-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("risk_category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload", models.FileField(upload_to="risk_information/")),
                ("geometry", models.JSONField(blank=True, null=True)),
                (
                    "risk_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_information",
                        to="risk_category.riskcategory",
                    ),
                ),
            ],
            options={
                "db_table": "risk_information",
            },
        ),
    ]
