# Generated by Django 6.0.2 on 2026-03-05 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_information", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskinformation",
            name="upload",
            field=models.FileField(
                upload_to="risk_information/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["geojson", "csv", "gpkg"]
                    )
                ],
            ),
        ),
    ]
