# Generated by Django 6.0.2 on 2026-03-05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("risk_information", "0002_alter_riskinformation_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskinformation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
    ]
