# Generated by Django 6.0.2 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_information", "0003_riskinformation_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskinformation",
            name="geometry_computed",
            field=models.BooleanField(default=False),
        ),
    ]
