# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("risk_information", "0005_riskinformation_country"),
        ("event_type_v2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskinformation",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risk_information",
                to="event_type_v2.eventtype",
            ),
        ),
    ]
