# Generated by Django 6.0.2 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_information", "0006_riskinformation_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskinformation",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
