# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0003_modelrun_models_m2m"),
        ("risk_information", "0007_riskinformation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskinformation",
            name="model_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risk_information",
                to="model.modelrun",
            ),
        ),
    ]
