# Generated by Django 6.0.2 on 2026-02-26 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0001_initial"),
        ("island", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="island",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="islands",
                to="country.country",
            ),
        ),
    ]
