# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("region", "0001_initial"),
        ("island", "0002_island_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="island",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="islands",
                to="region.region",
            ),
        ),
    ]
