# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("country", "0001_initial"),
        ("island", "0002_island_country"),
        ("region", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenScience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("captured_by", models.CharField(blank=True, max_length=255, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citizen_science",
                        to="country.country",
                    ),
                ),
                (
                    "island",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citizen_science",
                        to="island.island",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citizen_science",
                        to="region.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CitizenScienceMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="citizen_science/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "mp4",
                                    "mov",
                                    "avi",
                                    "mkv",
                                    "webm",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "citizen_science",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="citizen_science.citizenscience",
                    ),
                ),
            ],
        ),
    ]
